const { calcMarkupYMAndWriteFile } = require('../helpers');

test('calcMarkupYMAndWriteFile', async () => {
  const content = [
    {
      name: "G125 Fireworks-E27-2W Лампа светодиодная",
      retailPrice: 815,
      skuYm: "00-00000181",
      linkToImage: "https://cdn1.ozone.ru/s3/multimedia-r/6074081187.jpg",
      description: undefined,
      categoryInOurShope: "Лампочка светодиодная",
      brand: "Нет бренда",
      barcode: "",
      weightKg: "0.15",
      lenths: "35/35/12",
    },
    {
      name: "G125 Golden glass-E27-4W-2000K Лампа светодиодная",
      retailPrice: 815,
      skuYm: "00-00000183",
      linkToImage: "https://cdn1.ozone.ru/s3/multimedia-r/6074082627.jpg",
      description: undefined,
      categoryInOurShope: "Лампочка светодиодная",
      brand: "Нет бренда",
      barcode: "",
      weightKg: "0.15",
      lenths: "35/35/12",
    },
    {
      name: "G125 Leaves-E27-2W Лампа светодиодная",
      retailPrice: 815,
      skuYm: "00-00000185",
      linkToImage: "https://cdn1.ozone.ru/s3/multimedia-z/6074081303.jpg",
      description: undefined,
      categoryInOurShope: "Лампочка светодиодная",
      brand: "Нет бренда",
      barcode: "",
      weightKg: "0.15",
      lenths: "35/35/12",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 815,
      skuYm: "00-00000186",
      linkToImage: "https://cdn1.ozone.ru/s3/multimedia-7/6074080087.jpg",
      description: undefined,
      categoryInOurShope: "Лампочка светодиодная",
      brand: "Нет бренда",
      barcode: "",
      weightKg: "0.15",
      lenths: "35/35/12",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 100,
      skuYm: "00-1",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "1",
      lenths: "1/1/1",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 200,
      skuYm: "00-2",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "14",
      lenths: "1/1/1",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 300,
      skuYm: "00-3",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "15",
      lenths: "1/1/1",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 400,
      skuYm: "00-4",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "16",
      lenths: "1/1/1",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 500,
      skuYm: "00-5",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "14",
      lenths: "150/1/1",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 600,
      skuYm: "00-6",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "14",
      lenths: "1/150/1",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 700,
      skuYm: "00-7",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "14",
      lenths: "1/1/150",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 800,
      skuYm: "00-8",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "14",
      lenths: "149/1/1",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 900,
      skuYm: "00-9",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "14",
      lenths: "1/149/1",
    },
    {
      name: "G125 Love-E27-2W Лампа светодиодная",
      retailPrice: 1000,
      skuYm: "00-10",
      linkToImage: undefined,
      description: undefined,
      categoryInOurShope: undefined,
      brand: undefined,
      barcode: undefined,
      weightKg: "14",
      lenths: "1/1/149",
    },
  ];
  const result = await calcMarkupYMAndWriteFile(content);
  console.log(result);
  expect(result.length).toBe(14);
});